"""0001_initial_schema_obra_exemplar

Revision ID: 1ff02fc52fd6
Revises: 
Create Date: 2026-08-24 19:19:13.691724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1ff02fc52fd6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('obra',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('isbn', sa.String(length=20), nullable=False),
    sa.Column('titulo', sa.String(length=512), nullable=False),
    sa.Column('autores', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('editora', sa.String(length=256), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('capa_url', sa.String(length=1024), nullable=True),
    sa.Column('categoria', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exemplar',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('obra_id', sa.UUID(), nullable=False),
    sa.Column('codigo_qr', sa.String(length=256), nullable=False),
    sa.Column('estado', sa.Enum('disponivel', 'emprestado', 'baixado', name='estadoexemplar'), nullable=False),
    sa.Column('localizacao_estante', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['obra_id'], ['obra.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_qr', name='uq_exemplar_codigo_qr')
    )
    op.create_index(op.f('ix_exemplar_obra_id'), 'exemplar', ['obra_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exemplar_obra_id'), table_name='exemplar')
    op.drop_table('exemplar')
    op.drop_table('obra')
    # ### end Alembic commands ###
