"""0002_add_leitor

Revision ID: b9cb64000fbf
Revises: 1ff02fc52fd6
Create Date: 2026-08-24 20:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'b9cb64000fbf'
down_revision: Union[str, Sequence[str], None] = '1ff02fc52fd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'leitor',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('nome', sa.String(length=256), nullable=False),
        sa.Column('cpf_hash', sa.String(length=64), nullable=False),
        sa.Column('telefone', sa.String(length=32), nullable=True),
        sa.Column('email', sa.String(length=256), nullable=False),
        sa.Column('ativo', sa.Boolean(), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_leitor_cpf_hash'), 'leitor', ['cpf_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leitor_cpf_hash'), table_name='leitor')
    op.drop_table('leitor')
    # ### end Alembic commands ###
