from __future__ import annotations

from app.domain.services.configuracao_service import (
    CHAVE_DIAS_EMPRESTIMO,
    CHAVE_MAX_EMPRESTIMOS_POR_LEITOR,
    CHAVE_MAX_RENOVACOES,
    DEFAULT_DIAS_EMPRESTIMO,
    DEFAULT_MAX_EMPRESTIMOS_POR_LEITOR,
    DEFAULT_MAX_RENOVACOES,
    ConfiguracaoService,
)

__all__ = [
    "ConfiguracaoService",
    "CHAVE_DIAS_EMPRESTIMO",
    "CHAVE_MAX_RENOVACOES",
    "CHAVE_MAX_EMPRESTIMOS_POR_LEITOR",
    "DEFAULT_DIAS_EMPRESTIMO",
    "DEFAULT_MAX_RENOVACOES",
    "DEFAULT_MAX_EMPRESTIMOS_POR_LEITOR",
]
